#pragma once

#include "effect/attribute-types.h"
#include "monster-race/race-ability-flags.h"
#include "system/angband.h"
#include <map>

const std::map<MonsterAbilityType, AttributeType> Attribute_of_Ability = {
    { MonsterAbilityType::SHRIEK, AttributeType::NONE },
    { MonsterAbilityType::DISPEL, AttributeType::NONE },
    { MonsterAbilityType::ROCKET, AttributeType::ROCKET },
    { MonsterAbilityType::SHOOT, AttributeType::ARROW },
    { MonsterAbilityType::BR_ACID, AttributeType::ACID },
    { MonsterAbilityType::BR_ELEC, AttributeType::ELEC },
    { MonsterAbilityType::BR_FIRE, AttributeType::FIRE },
    { MonsterAbilityType::BR_COLD, AttributeType::COLD },
    { MonsterAbilityType::BR_POIS, AttributeType::POIS },
    { MonsterAbilityType::BR_NETH, AttributeType::NETHER },
    { MonsterAbilityType::BR_LITE, AttributeType::LITE },
    { MonsterAbilityType::BR_DARK, AttributeType::DARK },
    { MonsterAbilityType::BR_CONF, AttributeType::CONFUSION },
    { MonsterAbilityType::BR_SOUN, AttributeType::SOUND },
    { MonsterAbilityType::BR_CHAO, AttributeType::CHAOS },
    { MonsterAbilityType::BR_DISE, AttributeType::DISENCHANT },
    { MonsterAbilityType::BR_NEXU, AttributeType::NEXUS },
    { MonsterAbilityType::BR_TIME, AttributeType::TIME },
    { MonsterAbilityType::BR_INER, AttributeType::INERTIAL },
    { MonsterAbilityType::BR_GRAV, AttributeType::GRAVITY },
    { MonsterAbilityType::BR_SHAR, AttributeType::SHARDS },
    { MonsterAbilityType::BR_PLAS, AttributeType::PLASMA },
    { MonsterAbilityType::BR_FORC, AttributeType::FORCE },
    { MonsterAbilityType::BR_MANA, AttributeType::MANA },
    { MonsterAbilityType::BA_NUKE, AttributeType::NUKE },
    { MonsterAbilityType::BR_NUKE, AttributeType::NUKE },
    { MonsterAbilityType::BA_CHAO, AttributeType::CHAOS },
    { MonsterAbilityType::BR_DISI, AttributeType::DISINTEGRATE },
    { MonsterAbilityType::BA_ACID, AttributeType::ACID },
    { MonsterAbilityType::BA_ELEC, AttributeType::ELEC },
    { MonsterAbilityType::BA_FIRE, AttributeType::FIRE },
    { MonsterAbilityType::BA_COLD, AttributeType::COLD },
    { MonsterAbilityType::BA_POIS, AttributeType::POIS },
    { MonsterAbilityType::BA_NETH, AttributeType::NETHER },
    { MonsterAbilityType::BA_WATE, AttributeType::WATER },
    { MonsterAbilityType::BA_MANA, AttributeType::MANA },
    { MonsterAbilityType::BA_DARK, AttributeType::DARK },
    { MonsterAbilityType::DRAIN_MANA, AttributeType::DRAIN_MANA },
    { MonsterAbilityType::MIND_BLAST, AttributeType::MIND_BLAST },
    { MonsterAbilityType::BRAIN_SMASH, AttributeType::BRAIN_SMASH },
    { MonsterAbilityType::CAUSE_1, AttributeType::CAUSE_1 },
    { MonsterAbilityType::CAUSE_2, AttributeType::CAUSE_2 },
    { MonsterAbilityType::CAUSE_3, AttributeType::CAUSE_3 },
    { MonsterAbilityType::CAUSE_4, AttributeType::CAUSE_4 },
    { MonsterAbilityType::BO_ACID, AttributeType::ACID },
    { MonsterAbilityType::BO_ELEC, AttributeType::ELEC },
    { MonsterAbilityType::BO_FIRE, AttributeType::FIRE },
    { MonsterAbilityType::BO_COLD, AttributeType::COLD },
    { MonsterAbilityType::BA_LITE, AttributeType::LITE },
    { MonsterAbilityType::BO_NETH, AttributeType::NETHER },
    { MonsterAbilityType::BO_WATE, AttributeType::WATER },
    { MonsterAbilityType::BO_MANA, AttributeType::MANA },
    { MonsterAbilityType::BO_PLAS, AttributeType::PLASMA },
    { MonsterAbilityType::BO_ICEE, AttributeType::ICE },
    { MonsterAbilityType::MISSILE, AttributeType::MISSILE },
    { MonsterAbilityType::SCARE, AttributeType::NONE },
    { MonsterAbilityType::BLIND, AttributeType::NONE },
    { MonsterAbilityType::CONF, AttributeType::NONE },
    { MonsterAbilityType::SLOW, AttributeType::NONE },
    { MonsterAbilityType::HOLD, AttributeType::NONE },
    { MonsterAbilityType::HASTE, AttributeType::NONE },
    { MonsterAbilityType::HAND_DOOM, AttributeType::HAND_DOOM },
    { MonsterAbilityType::HEAL, AttributeType::NONE },
    { MonsterAbilityType::INVULNER, AttributeType::NONE },
    { MonsterAbilityType::BLINK, AttributeType::NONE },
    { MonsterAbilityType::TPORT, AttributeType::NONE },
    { MonsterAbilityType::WORLD, AttributeType::NONE },
    { MonsterAbilityType::SPECIAL, AttributeType::NONE },
    { MonsterAbilityType::TELE_TO, AttributeType::NONE },
    { MonsterAbilityType::TELE_AWAY, AttributeType::NONE },
    { MonsterAbilityType::TELE_LEVEL, AttributeType::NONE },
    { MonsterAbilityType::PSY_SPEAR, AttributeType::PSY_SPEAR },
    { MonsterAbilityType::DARKNESS, AttributeType::NONE },
    { MonsterAbilityType::TRAPS, AttributeType::NONE },
    { MonsterAbilityType::FORGET, AttributeType::NONE },
    { MonsterAbilityType::RAISE_DEAD, AttributeType::NONE },
    { MonsterAbilityType::S_KIN, AttributeType::NONE },
    { MonsterAbilityType::S_CYBER, AttributeType::NONE },
    { MonsterAbilityType::S_MONSTER, AttributeType::NONE },
    { MonsterAbilityType::S_MONSTERS, AttributeType::NONE },
    { MonsterAbilityType::S_ANT, AttributeType::NONE },
    { MonsterAbilityType::S_SPIDER, AttributeType::NONE },
    { MonsterAbilityType::S_HOUND, AttributeType::NONE },
    { MonsterAbilityType::S_HYDRA, AttributeType::NONE },
    { MonsterAbilityType::S_ANGEL, AttributeType::NONE },
    { MonsterAbilityType::S_DEMON, AttributeType::NONE },
    { MonsterAbilityType::S_UNDEAD, AttributeType::NONE },
    { MonsterAbilityType::S_DRAGON, AttributeType::NONE },
    { MonsterAbilityType::S_HI_UNDEAD, AttributeType::NONE },
    { MonsterAbilityType::S_HI_DRAGON, AttributeType::NONE },
    { MonsterAbilityType::S_AMBERITES, AttributeType::NONE },
    { MonsterAbilityType::S_UNIQUE, AttributeType::NONE },
    { MonsterAbilityType::BO_LITE, AttributeType::LITE },
    { MonsterAbilityType::BO_DARK, AttributeType::DARK },
    { MonsterAbilityType::DRAIN_LIFE, AttributeType::DRAIN_LIFE },
};

AttributeType get_ability_attribute(MonsterAbilityType ability);
