#pragma once

#include "monster-race/race-ability-flags.h"
#include "util/flag-group.h"

extern const EnumClassFlagGroup<MonsterAbilityType> MonsterAbilityType_SUMMON_MASK;
extern const EnumClassFlagGroup<MonsterAbilityType> MonsterAbilityType_INT_MASK;
extern const EnumClassFlagGroup<MonsterAbilityType> MonsterAbilityType_RIDING_MASK;
extern const EnumClassFlagGroup<MonsterAbilityType> MonsterAbilityType_BOLT_MASK;
extern const EnumClassFlagGroup<MonsterAbilityType> MonsterAbilityType_BEAM_MASK;
extern const EnumClassFlagGroup<MonsterAbilityType> MonsterAbilityType_BIG_BALL_MASK;
extern const EnumClassFlagGroup<MonsterAbilityType> MonsterAbilityType_BREATH_MASK;
extern const EnumClassFlagGroup<MonsterAbilityType> MonsterAbilityType_BALL_MASK;
extern const EnumClassFlagGroup<MonsterAbilityType> MonsterAbilityType_ATTACK_MASK;
extern const EnumClassFlagGroup<MonsterAbilityType> MonsterAbilityType_INDIRECT_MASK;
extern const EnumClassFlagGroup<MonsterAbilityType> MonsterAbilityType_NOMAGIC_MASK;
