#pragma once

enum class MonraceCorpseType {
    EAT_BLIND = 0,
    EAT_CONF = 1,
    EAT_MANA = 2,
    EAT_NEXUS = 3,
    EAT_SLEEP = 4,
    EAT_BERSERKER = 5,
    EAT_ACIDIC = 6,
    EAT_SPEED = 7,
    EAT_CURE = 8,
    EAT_FIRE_RES = 9,
    EAT_COLD_RES = 10,
    EAT_ACID_RES = 11,
    EAT_ELEC_RES = 12,
    EAT_POIS_RES = 13,
    EAT_INSANITY = 14,
    EAT_DRAIN_EXP = 15,
    EAT_POISONOUS = 16,
    EAT_GIVE_STR = 17,
    EAT_GIVE_INT = 18,
    EAT_GIVE_WIS = 19,
    EAT_GIVE_DEX = 20,
    EAT_GIVE_CON = 21,
    EAT_GIVE_CHR = 22,
    EAT_LOSE_STR = 23,
    EAT_LOSE_INT = 24,
    EAT_LOSE_WIS = 25,
    EAT_LOSE_DEX = 26,
    EAT_LOSE_CON = 27,
    EAT_LOSE_CHR = 28,
    EAT_DRAIN_MANA = 29,
    MAX,
};
